Update revshellgen.py
t0thkr1s/revshellgen pull request #7
Opened 2021-08-11 14:33 UTC by JohnRyk

2021-08-11 17:00 UTC, t0thkr1s commented
Hi!

First of all, thank you for contributing to the project!
Can you elaborate a bit more on this commit? Correct me if I'm wrong but sys.path[0] returns an empty string which makes no sense adding it before the commands directory path.

Have a great day!

2021-08-11 17:03 UTC, t0thkr1s requested changes

2021-08-11 17:03 UTC, t0thkr1s commented on revshellgen.py
> +commands = sorted([command for command in os.listdir(sys.path[0] + '/commands')])
sys.path[0] returns and empty string which makes no improvement to the script.

2021-08-12 01:54 UTC, JohnRyk commented
Hi. Thanks for reply. When I using the script I always put it into my "kit" folder such "/home/me/mykit" and create a sort link to the script like "/usr/bin/revshellgen". So when I run the command "revshellgen" the script cannot found the "commands" folder because it dose not in the "/usr/bin" folder. So add "sys.path[0]" and it can return the absolute path when I run the "revshellgen" command.

2021-08-14 07:30 UTC, t0thkr1s commented
Thanks for clarifying it! I reviewed and tested the code which actually makes sense and it's a nice little improvement. Adding support is always a good thing, so feel free to make contributions like this. 👍

2021-08-14 07:33 UTC, merged